// flow-typed signature: ecc6e29542f78c5e6c3f8614e219e20c
// flow-typed version: <<STUB>>/babel-plugin-react-native-web_v0.13.8/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-react-native-web'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-react-native-web' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-react-native-web/src/__tests__/index-test' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-native-web/src' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-native-web/src/moduleMap' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-react-native-web/index' {
  declare module.exports: $Exports<'babel-plugin-react-native-web'>;
}
declare module 'babel-plugin-react-native-web/index.js' {
  declare module.exports: $Exports<'babel-plugin-react-native-web'>;
}
declare module 'babel-plugin-react-native-web/src/__tests__/index-test.js' {
  declare module.exports: $Exports<'babel-plugin-react-native-web/src/__tests__/index-test'>;
}
declare module 'babel-plugin-react-native-web/src/index' {
  declare module.exports: $Exports<'babel-plugin-react-native-web/src'>;
}
declare module 'babel-plugin-react-native-web/src/index.js' {
  declare module.exports: $Exports<'babel-plugin-react-native-web/src'>;
}
declare module 'babel-plugin-react-native-web/src/moduleMap.js' {
  declare module.exports: $Exports<'babel-plugin-react-native-web/src/moduleMap'>;
}
