// flow-typed signature: 24acd96c27de67141b478977c93ab643
// flow-typed version: <<STUB>>/url-loader_v4.1.0/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'url-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'url-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'url-loader/dist/cjs' {
  declare module.exports: any;
}

declare module 'url-loader/dist' {
  declare module.exports: any;
}

declare module 'url-loader/dist/utils/normalizeFallback' {
  declare module.exports: any;
}

// Filename aliases
declare module 'url-loader/dist/cjs.js' {
  declare module.exports: $Exports<'url-loader/dist/cjs'>;
}
declare module 'url-loader/dist/index' {
  declare module.exports: $Exports<'url-loader/dist'>;
}
declare module 'url-loader/dist/index.js' {
  declare module.exports: $Exports<'url-loader/dist'>;
}
declare module 'url-loader/dist/utils/normalizeFallback.js' {
  declare module.exports: $Exports<'url-loader/dist/utils/normalizeFallback'>;
}
