// flow-typed signature: b6f99b317b6616d95c0864864085ff31
// flow-typed version: <<STUB>>/@babel/helper-validator-identifier_v7.10.4/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/helper-validator-identifier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/helper-validator-identifier' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/helper-validator-identifier/lib/identifier' {
  declare module.exports: any;
}

declare module '@babel/helper-validator-identifier/lib' {
  declare module.exports: any;
}

declare module '@babel/helper-validator-identifier/lib/keyword' {
  declare module.exports: any;
}

declare module '@babel/helper-validator-identifier/scripts/generate-identifier-regex' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/helper-validator-identifier/lib/identifier.js' {
  declare module.exports: $Exports<'@babel/helper-validator-identifier/lib/identifier'>;
}
declare module '@babel/helper-validator-identifier/lib/index' {
  declare module.exports: $Exports<'@babel/helper-validator-identifier/lib'>;
}
declare module '@babel/helper-validator-identifier/lib/index.js' {
  declare module.exports: $Exports<'@babel/helper-validator-identifier/lib'>;
}
declare module '@babel/helper-validator-identifier/lib/keyword.js' {
  declare module.exports: $Exports<'@babel/helper-validator-identifier/lib/keyword'>;
}
declare module '@babel/helper-validator-identifier/scripts/generate-identifier-regex.js' {
  declare module.exports: $Exports<'@babel/helper-validator-identifier/scripts/generate-identifier-regex'>;
}
