// flow-typed signature: b8ac7d04b05dddcf4c4c95f5347910a2
// flow-typed version: <<STUB>>/@babel/plugin-proposal-private-property-in-object_v7.10.4/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-proposal-private-property-in-object'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-proposal-private-property-in-object' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-proposal-private-property-in-object/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-proposal-private-property-in-object/lib/index' {
  declare module.exports: $Exports<'@babel/plugin-proposal-private-property-in-object/lib'>;
}
declare module '@babel/plugin-proposal-private-property-in-object/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-private-property-in-object/lib'>;
}
