// flow-typed signature: cfeb48b5c2be3c8a42e72139e15315f5
// flow-typed version: <<STUB>>/@babel/plugin-transform-flow-strip-types_v7.10.4/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-transform-flow-strip-types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-transform-flow-strip-types' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-transform-flow-strip-types/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-transform-flow-strip-types/lib/index' {
  declare module.exports: $Exports<'@babel/plugin-transform-flow-strip-types/lib'>;
}
declare module '@babel/plugin-transform-flow-strip-types/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-transform-flow-strip-types/lib'>;
}
