// flow-typed signature: 13f7c714b2ffd362c872ce4be5492886
// flow-typed version: <<STUB>>/@babel/plugin-proposal-private-methods_v7.10.4/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-proposal-private-methods'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-proposal-private-methods' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-proposal-private-methods/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-proposal-private-methods/lib/index' {
  declare module.exports: $Exports<'@babel/plugin-proposal-private-methods/lib'>;
}
declare module '@babel/plugin-proposal-private-methods/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-private-methods/lib'>;
}
