// flow-typed signature: 7e14423220305c5d8845623d79817f6a
// flow-typed version: <<STUB>>/@babel/plugin-proposal-nullish-coalescing-operator_v7.10.4/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-proposal-nullish-coalescing-operator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-proposal-nullish-coalescing-operator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-proposal-nullish-coalescing-operator/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-proposal-nullish-coalescing-operator/lib/index' {
  declare module.exports: $Exports<'@babel/plugin-proposal-nullish-coalescing-operator/lib'>;
}
declare module '@babel/plugin-proposal-nullish-coalescing-operator/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-nullish-coalescing-operator/lib'>;
}
