// flow-typed signature: 0039f5c845a3e00651413f0ec975ae45
// flow-typed version: <<STUB>>/@react-native-community/eslint-config_v^2.0.0/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@react-native-community/eslint-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@react-native-community/eslint-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@react-native-community/eslint-config/index' {
  declare module.exports: $Exports<'@react-native-community/eslint-config'>;
}
declare module '@react-native-community/eslint-config/index.js' {
  declare module.exports: $Exports<'@react-native-community/eslint-config'>;
}
