// flow-typed signature: bc3ea40e61ee8e00f14e42f41b9ea3b7
// flow-typed version: <<STUB>>/@storybook/react-native_v5.3.19/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/react-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/react-native' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/react-native/dist' {
  declare module.exports: any;
}

declare module '@storybook/react-native/dist/preview/components/OnDeviceUI/absolute-positioned-keyboard-aware-view' {
  declare module.exports: any;
}

declare module '@storybook/react-native/dist/preview/components/OnDeviceUI/addons' {
  declare module.exports: any;
}

declare module '@storybook/react-native/dist/preview/components/OnDeviceUI/addons/list' {
  declare module.exports: any;
}

declare module '@storybook/react-native/dist/preview/components/OnDeviceUI/addons/wrapper' {
  declare module.exports: any;
}

declare module '@storybook/react-native/dist/preview/components/OnDeviceUI/animation' {
  declare module.exports: any;
}

declare module '@storybook/react-native/dist/preview/components/OnDeviceUI' {
  declare module.exports: any;
}

declare module '@storybook/react-native/dist/preview/components/OnDeviceUI/navigation/bar' {
  declare module.exports: any;
}

declare module '@storybook/react-native/dist/preview/components/OnDeviceUI/navigation/button' {
  declare module.exports: any;
}

declare module '@storybook/react-native/dist/preview/components/OnDeviceUI/navigation/constants' {
  declare module.exports: any;
}

declare module '@storybook/react-native/dist/preview/components/OnDeviceUI/navigation' {
  declare module.exports: any;
}

declare module '@storybook/react-native/dist/preview/components/OnDeviceUI/navigation/visibility-button' {
  declare module.exports: any;
}

declare module '@storybook/react-native/dist/preview/components/OnDeviceUI/panel' {
  declare module.exports: any;
}

declare module '@storybook/react-native/dist/preview/components/Shared/text' {
  declare module.exports: any;
}

declare module '@storybook/react-native/dist/preview/components/Shared/theme' {
  declare module.exports: any;
}

declare module '@storybook/react-native/dist/preview/components/StoryListView' {
  declare module.exports: any;
}

declare module '@storybook/react-native/dist/preview/components/StoryView' {
  declare module.exports: any;
}

declare module '@storybook/react-native/dist/preview' {
  declare module.exports: any;
}

declare module '@storybook/react-native/dist/preview/rn-host-detect' {
  declare module.exports: any;
}

declare module '@storybook/react-native/dist/typings.d' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/react-native/dist/index' {
  declare module.exports: $Exports<'@storybook/react-native/dist'>;
}
declare module '@storybook/react-native/dist/index.js' {
  declare module.exports: $Exports<'@storybook/react-native/dist'>;
}
declare module '@storybook/react-native/dist/preview/components/OnDeviceUI/absolute-positioned-keyboard-aware-view.js' {
  declare module.exports: $Exports<'@storybook/react-native/dist/preview/components/OnDeviceUI/absolute-positioned-keyboard-aware-view'>;
}
declare module '@storybook/react-native/dist/preview/components/OnDeviceUI/addons/index' {
  declare module.exports: $Exports<'@storybook/react-native/dist/preview/components/OnDeviceUI/addons'>;
}
declare module '@storybook/react-native/dist/preview/components/OnDeviceUI/addons/index.js' {
  declare module.exports: $Exports<'@storybook/react-native/dist/preview/components/OnDeviceUI/addons'>;
}
declare module '@storybook/react-native/dist/preview/components/OnDeviceUI/addons/list.js' {
  declare module.exports: $Exports<'@storybook/react-native/dist/preview/components/OnDeviceUI/addons/list'>;
}
declare module '@storybook/react-native/dist/preview/components/OnDeviceUI/addons/wrapper.js' {
  declare module.exports: $Exports<'@storybook/react-native/dist/preview/components/OnDeviceUI/addons/wrapper'>;
}
declare module '@storybook/react-native/dist/preview/components/OnDeviceUI/animation.js' {
  declare module.exports: $Exports<'@storybook/react-native/dist/preview/components/OnDeviceUI/animation'>;
}
declare module '@storybook/react-native/dist/preview/components/OnDeviceUI/index' {
  declare module.exports: $Exports<'@storybook/react-native/dist/preview/components/OnDeviceUI'>;
}
declare module '@storybook/react-native/dist/preview/components/OnDeviceUI/index.js' {
  declare module.exports: $Exports<'@storybook/react-native/dist/preview/components/OnDeviceUI'>;
}
declare module '@storybook/react-native/dist/preview/components/OnDeviceUI/navigation/bar.js' {
  declare module.exports: $Exports<'@storybook/react-native/dist/preview/components/OnDeviceUI/navigation/bar'>;
}
declare module '@storybook/react-native/dist/preview/components/OnDeviceUI/navigation/button.js' {
  declare module.exports: $Exports<'@storybook/react-native/dist/preview/components/OnDeviceUI/navigation/button'>;
}
declare module '@storybook/react-native/dist/preview/components/OnDeviceUI/navigation/constants.js' {
  declare module.exports: $Exports<'@storybook/react-native/dist/preview/components/OnDeviceUI/navigation/constants'>;
}
declare module '@storybook/react-native/dist/preview/components/OnDeviceUI/navigation/index' {
  declare module.exports: $Exports<'@storybook/react-native/dist/preview/components/OnDeviceUI/navigation'>;
}
declare module '@storybook/react-native/dist/preview/components/OnDeviceUI/navigation/index.js' {
  declare module.exports: $Exports<'@storybook/react-native/dist/preview/components/OnDeviceUI/navigation'>;
}
declare module '@storybook/react-native/dist/preview/components/OnDeviceUI/navigation/visibility-button.js' {
  declare module.exports: $Exports<'@storybook/react-native/dist/preview/components/OnDeviceUI/navigation/visibility-button'>;
}
declare module '@storybook/react-native/dist/preview/components/OnDeviceUI/panel.js' {
  declare module.exports: $Exports<'@storybook/react-native/dist/preview/components/OnDeviceUI/panel'>;
}
declare module '@storybook/react-native/dist/preview/components/Shared/text.js' {
  declare module.exports: $Exports<'@storybook/react-native/dist/preview/components/Shared/text'>;
}
declare module '@storybook/react-native/dist/preview/components/Shared/theme.js' {
  declare module.exports: $Exports<'@storybook/react-native/dist/preview/components/Shared/theme'>;
}
declare module '@storybook/react-native/dist/preview/components/StoryListView/index' {
  declare module.exports: $Exports<'@storybook/react-native/dist/preview/components/StoryListView'>;
}
declare module '@storybook/react-native/dist/preview/components/StoryListView/index.js' {
  declare module.exports: $Exports<'@storybook/react-native/dist/preview/components/StoryListView'>;
}
declare module '@storybook/react-native/dist/preview/components/StoryView/index' {
  declare module.exports: $Exports<'@storybook/react-native/dist/preview/components/StoryView'>;
}
declare module '@storybook/react-native/dist/preview/components/StoryView/index.js' {
  declare module.exports: $Exports<'@storybook/react-native/dist/preview/components/StoryView'>;
}
declare module '@storybook/react-native/dist/preview/index' {
  declare module.exports: $Exports<'@storybook/react-native/dist/preview'>;
}
declare module '@storybook/react-native/dist/preview/index.js' {
  declare module.exports: $Exports<'@storybook/react-native/dist/preview'>;
}
declare module '@storybook/react-native/dist/preview/rn-host-detect.js' {
  declare module.exports: $Exports<'@storybook/react-native/dist/preview/rn-host-detect'>;
}
declare module '@storybook/react-native/dist/typings.d.js' {
  declare module.exports: $Exports<'@storybook/react-native/dist/typings.d'>;
}
